"""Spectr gallery home-screen template mapping (61 Awesome iOS Design apps).

Each app maps to a layout template derived from https://www.spectr.to/gallery/{slug}
phone-screen preview (iframe srcDoc). Regenerate signatures with fetch_spectr_homes.py.
"""

from __future__ import annotations

# app display name -> template id
APP_SPECTR_TEMPLATE: dict[str, str] = {
    "WhatsApp": "whatsapp_chat",
    "Signal": "signal_thread",
    "Telegram": "telegram_chat",
    "Messenger": "messenger_thread",
    "Discord": "discord_rail",
    "Teams": "teams_home",
    "Instagram": "instagram_feed",
    "TikTok": "tiktok_video",
    "Snapchat": "snapchat_camera",
    "X": "x_feed",
    "Reddit": "reddit_feed",
    "LinkedIn": "linkedin_feed",
    "Facebook": "facebook_feed",
    "Threads": "threads_feed",
    "Pinterest": "pinterest_masonry",
    "Tinder": "tinder_swipe",
    "Bumble": "bumble_swipe",
    "Hinge": "hinge_profile",
    "Happn": "happn_timeline",
    "Spotify": "spotify_np",
    "Apple Music": "apple_music_np",
    "Deezer": "deezer_np",
    "SoundCloud": "soundcloud_np",
    "YouTube Music": "ytmusic_np",
    "Shazam": "shazam_listen",
    "Audible": "audible_home",
    "YouTube": "youtube_feed",
    "Netflix": "netflix_hero",
    "Disney+": "disney_billboard",
    "Prime Video": "prime_billboard",
    "Apple TV": "appletv_home",
    "Twitch": "twitch_player",
    "ChatGPT": "ai_chatgpt",
    "Gemini": "ai_gemini",
    "Claude": "ai_claude",
    "Perplexity": "ai_perplexity",
    "Grok": "ai_grok",
    "Revolut": "finance_revolut",
    "Banque": "finance_revolut",
    "Wise": "finance_wise",
    "PayPal": "finance_paypal",
    "Binance": "finance_binance",
    "Coinbase": "finance_coinbase",
    "Amazon": "commerce_amazon",
    "Uber": "uber_map",
    "Uber Eats": "food_eats",
    "Deliveroo": "food_deliveroo",
    "Waze": "maps_waze",
    "Google Maps": "maps_google",
    "Plans": "maps_google",
    "Booking": "travel_booking",
    "Airbnb": "travel_airbnb",
    "Expedia": "travel_expedia",
    "Flighty": "travel_flighty",
    "TripAdvisor": "travel_tripadvisor",
    "Strava": "fitness_strava",
    "Google Calendar": "calendar_home",
    "Dropbox": "files_dropbox",
    "Fichiers": "files_dropbox",
    "Zoom": "meetings_zoom",
    "Kindle": "reader_kindle",
}

CATEGORY_DEFAULT_TEMPLATE: dict[str, str] = {
    "messaging": "messaging_chat",
    "social": "social_feed",
    "short-video": "tiktok_video",
    "ride": "uber_map",
    "maps": "maps_google",
    "travel": "travel_airbnb",
    "video": "netflix_hero",
    "music": "spotify_np",
    "finance": "finance_revolut",
    "dating": "tinder_swipe",
    "ai": "ai_chatgpt",
    "commerce": "commerce_amazon",
    "food": "food_eats",
    "fitness": "fitness_strava",
    "calendar": "calendar_home",
    "meetings": "meetings_zoom",
    "files": "files_dropbox",
    "reader": "reader_kindle",
    "shazam": "shazam_listen",
    "youtube": "youtube_feed",
    "discord": "discord_rail",
    "productivity": "files_dropbox",
    "misc": "social_feed",
}


def template_for_app(app_name: str, category: str) -> str:
    return APP_SPECTR_TEMPLATE.get(app_name, CATEGORY_DEFAULT_TEMPLATE.get(category, "social_feed"))
