"""Swift UI templates for Awesome app generation — quasi-conformant DESIGN-swiftui.md."""

from __future__ import annotations

import re
from typing import Sequence


def slug(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]", "", name)


def extract_colors(md: str) -> list[tuple[str, str]]:
    colors: list[tuple[str, str]] = []
    in_block = False
    for line in md.splitlines():
        if "extension Color" in line and "LinearGradient" not in line:
            in_block = True
            continue
        if in_block and line.strip() == "```":
            break
        if in_block:
            m = re.match(r"\s*static let (\w+)\s*=\s*(.+)$", line)
            if m:
                expr = m.group(2).rstrip()
                if expr.startswith("Color(") or expr == "Color.white" or expr.startswith("Color."):
                    colors.append((m.group(1), expr))
    return colors


def extract_fonts(md: str) -> list[tuple[str, str]]:
    fonts: list[tuple[str, str]] = []
    in_block = False
    for line in md.splitlines():
        if "extension Font" in line:
            in_block = True
            continue
        if in_block and line.strip() == "```":
            break
        if in_block:
            m = re.match(r"\s*static let (\w+)\s*=\s*(.+)$", line)
            if m:
                expr = m.group(2).rstrip()
                # Fallback proprietary fonts → SF Pro system
                sys_m = re.search(r"size:\s*(\d+(?:\.\d+)?)", expr)
                weight_m = re.search(r"weight:\s*(\.\w+)", expr)
                size = sys_m.group(1) if sys_m else "17"
                weight = weight_m.group(1) if weight_m else ".regular"
                fonts.append((m.group(1), f"Font.system(size: {size}, weight: {weight})"))
    return fonts


def extract_tabs(md: str) -> list[tuple[str, str]]:
    tab_items: list[tuple[str, str]] = []
    pattern = re.compile(
        r"struct (\w+(?:TabView|RootTabView|RootView))\s*:\s*View\s*\{.*?\n\s*var body: some View \{(.*?)\n\s*\}\n\}",
        re.DOTALL,
    )
    m = pattern.search(md)
    if m:
        body = m.group(2)
        for lm in re.finditer(r'Label\("([^"]+)", systemImage: "([^"]+)"\)', body):
            tab_items.append((lm.group(1), lm.group(2)))
    return tab_items


def pick_color(colors: Sequence[tuple[str, str]], *keywords: str, default_idx: int = 0) -> str:
    for kw in keywords:
        for name, _ in colors:
            if kw.lower() in name.lower():
                return name
    return colors[default_idx][0] if colors else "accent"


def pick_font(fonts: Sequence[tuple[str, str]], *keywords: str, default_idx: int = 0) -> str:
    for kw in keywords:
        for name, _ in fonts:
            if kw.lower() in name.lower():
                return name
    return fonts[default_idx][0] if fonts else "body"


def category_from_path(rel: str) -> str:
    top = rel.split("/")[0]
    name = rel.split("/")[-1]
    if name in ("uber-eats", "deliveroo"):
        return "food"
    if name in ("chatgpt", "gemini", "claude", "perplexity", "grok"):
        return "ai"
    if name in ("amazon",):
        return "commerce"
    if name in ("kindle",):
        return "reader"
    if name in ("shazam",):
        return "shazam"
    if name in ("google-maps", "waze", "uber"):
        return "maps"
    if name in ("booking", "airbnb", "expedia", "flighty", "tripadvisor"):
        return "travel"
    if name in ("google-calendar",):
        return "calendar"
    if name in ("dropbox",):
        return "files"
    if name in ("zoom", "microsoft-teams"):
        return "meetings"
    if top == "food":
        return "food"
    return top


def normalize_token_expr(expr: str) -> str:
    """Design specs use Color.token — in our private enum, reference sibling static lets."""
    expr = expr.strip()
    if re.match(r"Color\.(white|black|clear|primary|secondary|accentColor)\b", expr):
        return expr
    m = re.match(r"Color\.(\w+)(.*)$", expr)
    if m:
        return m.group(1) + m.group(2)
    return expr


def tokens_block(slug_name: str, colors: list[tuple[str, str]], fonts: list[tuple[str, str]]) -> str:
    clines = []
    for n, e in colors[:32]:
        clines.append(f"    static let {n} = {normalize_token_expr(e)}")
    cl = "\n".join(clines) or "    static let accent = Color.accentColor"
    fl = "\n".join(f"    static let {n} = {e}" for n, e in fonts[:16]) or "    static let body = Font.system(size: 17)"
    return f"""private enum {slug_name}Tokens {{
{cl}
}}

private enum {slug_name}Fonts {{
{fl}
}}"""


def header(app_name: str, rel_path: str) -> str:
    return f"""import SwiftUI

// Quasi-conformant UI — Meliwat/awesome-ios-design-md/{rel_path}/DESIGN-swiftui.md
// Generated by generate_awesome_apps_v2.py — do not edit by hand
"""


def tab_view(slug_name: str, tabs: list[tuple[str, str]], tint: str, screens: str) -> str:
    items = "\n".join(
        f'            {slug_name}TabHost(title: "{t}", icon: "{i}") {{ {slug_name}ScreenFactory.screen(for: "{t}") }}\n'
        f'                .tabItem {{ Label("{t}", systemImage: "{i}") }}'
        for t, i in tabs[:5]
    )
    return f"""struct LpspAwesome{slug_name}View: View {{
    var body: some View {{
        TabView {{
{items}
        }}
        .tint({slug_name}Tokens.{tint})
    }}
}}

private struct {slug_name}TabHost<Content: View>: View {{
    let title: String
    let icon: String
    @ViewBuilder var content: () -> Content
    var body: some View {{ content() }}
}}

private enum {slug_name}ScreenFactory {{
    @ViewBuilder
    static func screen(for tab: String) -> some View {{
        switch tab.lowercased() {{
{screens}
        default:
            {slug_name}GenericListScreen(title: tab)
        }}
    }}
}}"""


# ---------- MESSAGING ----------

def gen_messaging(slug_name: str, app_name: str, colors, fonts, tabs, rel) -> str:
    p = pick_color(colors, "green", "brand", "accent", "blue", "primary")
    canvas = pick_color(colors, "canvasLight", "canvas", "background", "surface")
    canvas_dark = pick_color(colors, "canvasDark", "wallpaperDark", "surface1Dark", default_idx=0)
    outgoing = pick_color(colors, "outgoing", "bubble", "brand", default_idx=0)
    incoming = pick_color(colors, "incomingLight", "incoming", "surface", default_idx=0)
    text_pri = pick_color(colors, "textPrimary", "text", default_idx=0)
    text_sec = pick_color(colors, "textSecondary", "secondary", default_idx=0)
    wallpaper = pick_color(colors, "wallpaper", "wallpaperLight", "canvasLight", default_idx=0)

    chat_tab = next((t for t, _ in tabs if "chat" in t.lower() or "message" in t.lower()), tabs[0][0] if tabs else "Chats")

    screens = f'''        case let t where t.contains("chat") || t.contains("message"):
            {slug_name}ChatsScreen()
        case let t where t.contains("call") || t.contains("phone"):
            {slug_name}CallsScreen()
        case let t where t.contains("setting"):
            {slug_name}SettingsScreen()'''

    chats = f"""
private struct {slug_name}ChatsScreen: View {{
    @State private var selected: {slug_name}ChatThread? = nil
    private let threads = {slug_name}DemoData.threads

    var body: some View {{
        NavigationStack {{
            List(threads) {{ thread in
                Button {{ selected = thread }} label: {{
                    {slug_name}ChatRow(thread: thread)
                }}
                .buttonStyle(.plain)
                .listRowInsets(EdgeInsets(top: 8, leading: 16, bottom: 8, trailing: 16))
                .listRowSeparatorTint({slug_name}Tokens.{pick_color(colors, "divider", "hairline", default_idx=0)}.opacity(0.5))
            }}
            .listStyle(.plain)
            .navigationTitle("{chat_tab}")
            .toolbar {{
                ToolbarItem(placement: .topBarTrailing) {{
                    Button {{}} label: {{ Image(systemName: "square.and.pencil") }}
                }}
            }}
            .navigationDestination(item: $selected) {{ thread in
                {slug_name}ChatDetailScreen(thread: thread)
            }}
        }}
    }}
}}

private struct {slug_name}ChatRow: View {{
    let thread: {slug_name}ChatThread
    var body: some View {{
        HStack(spacing: 12) {{
            Circle()
                .fill(thread.avatarColor.gradient)
                .frame(width: 48, height: 48)
                .overlay(Text(thread.initials).font(.system(size: 18, weight: .semibold)).foregroundStyle(.white))
                .overlay(Circle().strokeBorder({slug_name}Tokens.{p}, lineWidth: thread.unread > 0 ? 2.5 : 0))
            VStack(alignment: .leading, spacing: 4) {{
                HStack {{
                    Text(thread.name).font({slug_name}Fonts.{pick_font(fonts, "contact", "nav", "body")}).foregroundStyle({slug_name}Tokens.{text_pri})
                    Spacer()
                    Text(thread.time).font(.system(size: 12)).foregroundStyle({slug_name}Tokens.{text_sec})
                }}
                HStack {{
                    Text(thread.preview).font(.system(size: 15)).foregroundStyle({slug_name}Tokens.{text_sec}).lineLimit(1)
                    Spacer()
                    if thread.unread > 0 {{
                        Text("\\(thread.unread)").font(.system(size: 12, weight: .semibold)).foregroundStyle(.white)
                            .padding(.horizontal, 7).padding(.vertical, 3)
                            .background(Capsule().fill({slug_name}Tokens.{p}))
                    }}
                }}
            }}
        }}
        .frame(height: 56)
    }}
}}

private struct {slug_name}ChatDetailScreen: View {{
    let thread: {slug_name}ChatThread
    @State private var draft = ""
    var body: some View {{
        VStack(spacing: 0) {{
            ScrollView {{
                VStack(spacing: 8) {{
                    {slug_name}SystemBanner(text: "Messages are end-to-end encrypted.")
                    ForEach(thread.messages) {{ msg in
                        if msg.outgoing {{
                            {slug_name}OutgoingBubble(text: msg.text, time: msg.time, accent: {slug_name}Tokens.{outgoing}, textColor: {slug_name}Tokens.{text_pri}, readColor: {slug_name}Tokens.{pick_color(colors, "read", "blue", default_idx=0)})
                        }} else {{
                            {slug_name}IncomingBubble(text: msg.text, time: msg.time, fill: {slug_name}Tokens.{incoming}, textColor: {slug_name}Tokens.{text_pri})
                        }}
                    }}
                }}
                .padding(.vertical, 12)
            }}
            .background({slug_name}Tokens.{wallpaper})
            {slug_name}ComposeBar(text: $draft, accent: {slug_name}Tokens.{p})
        }}
        .navigationTitle(thread.name)
        .navigationBarTitleDisplayMode(.inline)
    }}
}}

private struct {slug_name}OutgoingBubble: View {{
    let text: String; let time: String; let accent: Color; let textColor: Color; let readColor: Color
    var body: some View {{
        HStack {{
            Spacer(minLength: 60)
            VStack(alignment: .trailing, spacing: 4) {{
                Text(text).font(.system(size: 17)).foregroundStyle(textColor)
                HStack(spacing: 3) {{
                    Text(time).font(.system(size: 11)).foregroundStyle(textColor.opacity(0.6))
                    Image(systemName: "checkmark").font(.system(size: 11, weight: .bold)).foregroundStyle(readColor)
                    Image(systemName: "checkmark").font(.system(size: 11, weight: .bold)).foregroundStyle(readColor).offset(x: -6)
                }}
            }}
            .padding(.vertical, 8).padding(.horizontal, 12)
            .background(UnevenRoundedRectangle(topLeadingRadius: 12, bottomLeadingRadius: 12, bottomTrailingRadius: 0, topTrailingRadius: 12).fill(accent))
        }}
        .padding(.horizontal, 8)
    }}
}}

private struct {slug_name}IncomingBubble: View {{
    let text: String; let time: String; let fill: Color; let textColor: Color
    var body: some View {{
        HStack {{
            VStack(alignment: .leading, spacing: 4) {{
                Text(text).font(.system(size: 17)).foregroundStyle(textColor)
                Text(time).font(.system(size: 11)).foregroundStyle(textColor.opacity(0.6))
            }}
            .padding(.vertical, 8).padding(.horizontal, 12)
            .background(UnevenRoundedRectangle(topLeadingRadius: 12, bottomLeadingRadius: 0, bottomTrailingRadius: 12, topTrailingRadius: 12).fill(fill))
            Spacer(minLength: 60)
        }}
        .padding(.horizontal, 8)
    }}
}}

private struct {slug_name}ComposeBar: View {{
    @Binding var text: String
    let accent: Color
    var body: some View {{
        HStack(spacing: 12) {{
            Image(systemName: "face.smiling").font(.system(size: 22)).foregroundStyle(.secondary)
            TextField("Message", text: $text, axis: .vertical)
                .padding(.horizontal, 14).padding(.vertical, 8)
                .background(RoundedRectangle(cornerRadius: 20).fill(Color(.systemBackground)))
            Button {{}} label: {{
                Image(systemName: text.isEmpty ? "mic.fill" : "paperplane.fill")
                    .font(.system(size: 18, weight: .semibold)).foregroundStyle(.white)
                    .frame(width: 36, height: 36).background(Circle().fill(accent))
            }}
        }}
        .padding(.horizontal, 12).padding(.vertical, 8)
        .background(.bar)
    }}
}}

private struct {slug_name}SystemBanner: View {{
    let text: String
    var body: some View {{
        Text(text).font(.system(size: 12, weight: .medium)).foregroundStyle(.secondary)
            .padding(.horizontal, 12).padding(.vertical, 6)
            .background(Capsule().fill(Color(.systemBackground).opacity(0.9)))
    }}
}}

private struct {slug_name}CallsScreen: View {{
    var body: some View {{
        NavigationStack {{
            List({slug_name}DemoData.threads) {{ t in
                HStack(spacing: 12) {{
                    Circle().fill(t.avatarColor.gradient).frame(width: 40, height: 40)
                        .overlay(Text(t.initials).foregroundStyle(.white))
                    VStack(alignment: .leading) {{
                        Text(t.name).font(.system(size: 17, weight: .semibold))
                        Text("Outgoing").font(.system(size: 14)).foregroundStyle(.secondary)
                    }}
                    Spacer()
                    Image(systemName: "phone.fill").foregroundStyle({slug_name}Tokens.{p})
                }}
            }}
            .navigationTitle("Calls")
        }}
    }}
}}

private struct {slug_name}SettingsScreen: View {{
    var body: some View {{
        NavigationStack {{
            List {{
                Section("Account") {{
                    Label("Profile", systemImage: "person.circle")
                    Label("Privacy", systemImage: "lock")
                    Label("Notifications", systemImage: "bell")
                }}
                Section("Chats") {{
                    Label("Wallpaper", systemImage: "photo")
                    Label("Backup", systemImage: "arrow.clockwise.icloud")
                }}
            }}
            .navigationTitle("Settings")
        }}
    }}
}}
"""

    support = f"""
private struct {slug_name}GenericListScreen: View {{
    let title: String
    var body: some View {{
        NavigationStack {{
            List(0..<8, id: \\.self) {{ i in
                HStack {{
                    RoundedRectangle(cornerRadius: 8).fill({slug_name}Tokens.{p}.opacity(0.15)).frame(width: 44, height: 44)
                    VStack(alignment: .leading) {{
                        Text("\\(title) \\(i + 1)").font(.system(size: 17, weight: .semibold))
                        Text("Updated recently").font(.system(size: 14)).foregroundStyle(.secondary)
                    }}
                }}
            }}
            .navigationTitle(title)
        }}
    }}
}}

private struct {slug_name}ChatThread: Identifiable, Hashable {{
    let id = UUID()
    let name: String
    let initials: String
    let preview: String
    let time: String
    let unread: Int
    let avatarColor: Color
    let messages: [{slug_name}ChatMessage]
}}

private struct {slug_name}ChatMessage: Identifiable, Hashable {{
    let id = UUID()
    let text: String
    let time: String
    let outgoing: Bool
}}

private enum {slug_name}DemoData {{
    static let threads: [{slug_name}ChatThread] = [
        .init(name: "Alex Martin", initials: "AM", preview: "On se voit ce soir ?", time: "10:24", unread: 2, avatarColor: .blue, messages: [
            .init(text: "Salut ! Tu es dispo ?", time: "10:20", outgoing: false),
            .init(text: "Oui, vers 19h ?", time: "10:22", outgoing: true),
            .init(text: "On se voit ce soir ?", time: "10:24", outgoing: false),
        ]),
        .init(name: "Équipe projet", initials: "EP", preview: "Documents envoyés ✓", time: "09:15", unread: 0, avatarColor: .purple, messages: [
            .init(text: "Voici les fichiers", time: "09:10", outgoing: false),
            .init(text: "Merci, je regarde", time: "09:12", outgoing: true),
        ]),
        .init(name: "Marie Dupont", initials: "MD", preview: "👍", time: "Hier", unread: 0, avatarColor: .pink, messages: [
            .init(text: "C'est bon pour demain", time: "18:40", outgoing: true),
            .init(text: "👍", time: "18:41", outgoing: false),
        ]),
    ]
}}
"""

    if not tabs:
        tabs = [("Chats", "message.fill"), ("Calls", "phone.fill"), ("Settings", "gearshape.fill")]

    return (
        header(app_name, rel)
        + tab_view(slug_name, tabs, p, screens)
        + "\n"
        + tokens_block(slug_name, colors, fonts)
        + chats
        + support
    )


# Due to length, additional category generators are in generate_awesome_apps_v2.py
