#!/usr/bin/env python3
"""Remplace les chaînes UI anglaises courantes par du français dans Apps/Clone."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "LostPhone" / "Apps" / "Clone"

REPLACEMENTS = [
    ('Button("Edit")', 'Button("Modifier")'),
    ('Button("Done")', 'Button("Terminé")'),
    ('Button("Cancel")', 'Button("Annuler")'),
    ('Button("Send")', 'Button("Envoyer")'),
    ('Button("Select")', 'Button("Sélectionner")'),
    ('Button("See All")', 'Button("Tout afficher")'),
    ('Button("Add Number")', 'Button("Ajouter un numéro")'),
    ('Button("Groups")', 'Button("Groupes")'),
    ('Button("Greeting")', 'Button("Message d\'accueil")'),
    ('Text("All")', 'Text("Tous")'),
    ('Text("Missed")', 'Text("Manqués")'),
    ('Text("My Card")', 'Text("Ma carte")'),
    ('Text("Call Voicemail")', 'Text("Appeler la messagerie")'),
    ('Text("Updated Just Now")', 'Text("Mis à jour à l\'instant")'),
    ('Text("To:")', 'Text("À :")'),
    ('Text("Cc/Bcc:")', 'Text("Cc/Cci :")'),
    ('Text("Subject:")', 'Text("Objet :")'),
    ('Label("Trash"', 'Label("Corbeille"'),
    ('Label("Flag"', 'Label("Signaler"'),
    ('Label("Unread"', 'Label("Non lu"'),
    ('Label("Read"', 'Label("Lu"'),
    ('navigationTitle("Notes")', 'navigationTitle("Notes")'),
    ('Text("iCloud")', 'Text("iCloud")'),
    ('Text("New Note")', 'Text("Nouvelle note")'),
    ('Text("No additional text")', 'Text("Aucun texte supplémentaire")'),
    ('Text("Suggestions")', 'Text("Suggestions")'),
    ('Text("Select")', 'Text("Sélectionner")'),
    ('Button("Today")', 'Button("Aujourd\'hui")'),
    ('Button("Calendars")', 'Button("Calendriers")'),
    ('Button("Inbox")', 'Button("Boîte de réception")'),
    ('Text("Starts")', 'Text("Début")'),
    ('Text("Ends")', 'Text("Fin")'),
    ('Text("Location")', 'Text("Lieu")'),
    ('Section(header: Text("Notes"))', 'Section(header: Text("Notes"))'),
    ('placeholder: "Search or enter website"', 'placeholder: "Rechercher ou saisir un site"'),
    ('Text("Search or enter website")', 'Text("Rechercher ou saisir un site"'),
    ('Text("Tabs")', 'Text("Onglets")'),
    ('Text("Recent Searches")', 'Text("Recherches récentes")'),
    ('Text("Favorites")', 'Text("Favoris")'),
    ('Text("Privacy Report")', 'Text("Rapport de confidentialité")'),
    ('Text("Trackers Prevented")', 'Text("Traqueurs bloqués")'),
    ('Text("VIDEO")', 'Text("VIDÉO")'),
    ('Text("PHOTO")', 'Text("PHOTO")'),
    ('Text("Lap")', 'Text("Tour")'),
    ('Text("Reset")', 'Text("Réinitialiser")'),
    ('Text("Stop")', 'Text("Stop")'),
    ('Text("Start")', 'Text("Démarrer")'),
    ('Text("Pause")', 'Text("Pause")'),
    ('Text("No Alarm")', 'Text("Pas d\'alarme")'),
    ('Text("Other")', 'Text("Autres")'),
    ('Text("SET UP")', 'Text("CONFIGURER")'),
    ('Text("hours")', 'Text("h")'),
    ('Text("min")', 'Text("min")'),
    ('Text("sec")', 'Text("s")'),
    ('TextField("Label"', 'TextField("Nom"'),
    ('Label("Today"', 'Label("Aujourd\'hui"'),
    ('Label("Games"', 'Label("Jeux"'),
    ('Label("Apps"', 'Label("Apps"'),
    ('Text("Today")', 'Text("Aujourd\'hui")'),
    ('Text("Must-Have Apps")', 'Text("Apps incontournables")'),
    ('Text("Now Trending")', 'Text("Tendances")'),
    ('Text("Top Paid")', 'Text("Top payantes")'),
    ('Text("Popular Games")', 'Text("Jeux populaires")'),
    ('Text("Discover")', 'Text("Découvrir")'),
    ('Text("Suggested")', 'Text("Suggestions")'),
    ('Text("What\'s New")', 'Text("Nouveautés")'),
    ('Text("Ratings")', 'Text("Notes")'),
    ('Text("Purchased")', 'Text("Achats")'),
    ('Text("Subscriptions")', 'Text("Abonnements")'),
    ('Text("Sign Out")', 'Text("Se déconnecter")'),
    ('Text("Done")', 'Text("Terminé")'),
    ('Text("GET")', 'Text("OBTENIR")'),
    ('Text("OPEN")', 'Text("OUVRIR")'),
    ('Text("Downloaded")', 'Text("Téléchargé")'),
    ('Text("Artists")', 'Text("Artistes")'),
    ('Text("Songs")', 'Text("Morceaux")'),
    ('Text("Albums")', 'Text("Albums")'),
    ('Text("Recently Added")', 'Text("Ajouts récents")'),
    ('Text("Hourly Forecast")', 'Text("Prévisions horaires")'),
    ('Text("10-Day Forecast")', 'Text("Prévisions sur 10 jours")'),
    ('Text("Mostly Clear")', 'Text("Plutôt dégagé")'),
    ('Text("Cupertino")', 'Text("Cupertino")'),
    ('SettingsIcon(title: "Airplane Mode"', 'SettingsIcon(title: "Mode Avion"'),
    ('SettingsIcon(title: "Wi-Fi"', 'SettingsIcon(title: "Wi‑Fi"'),
    ('SettingsIcon(title: "Bluetooth"', 'SettingsIcon(title: "Bluetooth"'),
    ('SettingsIcon(title: "Cellular"', 'SettingsIcon(title: "Cellulaire"'),
    ('SettingsIcon(title: "Personal Hotspot"', 'SettingsIcon(title: "Partage de connexion"'),
    ('SettingsIcon(title: "Notifications"', 'SettingsIcon(title: "Notifications"'),
    ('SettingsIcon(title: "Sounds & Haptics"', 'SettingsIcon(title: "Sons et vibrations"'),
    ('SettingsIcon(title: "Focus"', 'SettingsIcon(title: "Concentration"'),
    ('SettingsIcon(title: "Screen Time"', 'SettingsIcon(title: "Temps d\'écran"'),
    ('SettingsIcon(title: "General"', 'SettingsIcon(title: "Général"'),
    ('SettingsIcon(title: "Control Center"', 'SettingsIcon(title: "Centre de contrôle"'),
    ('SettingsIcon(title: "Display & Brightness"', 'SettingsIcon(title: "Écran et luminosité"'),
    ('SettingsIcon(title: "Home Screen & App Library"', 'SettingsIcon(title: "Écran d\'accueil et bibliothèque d\'apps"'),
    ('SettingsIcon(title: "Accessibility"', 'SettingsIcon(title: "Accessibilité"'),
    ('SettingsIcon(title: "Wallpaper"', 'SettingsIcon(title: "Fond d\'écran"'),
    ('SettingsIcon(title: "StandBy"', 'SettingsIcon(title: "Veille"'),
    ('SettingsIcon(title: "Battery"', 'SettingsIcon(title: "Batterie"'),
    ('SettingsIcon(title: "Privacy & Security"', 'SettingsIcon(title: "Confidentialité et sécurité"'),
    ('SettingsIcon(title: "App Store"', 'SettingsIcon(title: "App Store"'),
    ('SettingsIcon(title: "Wallet & Apple Pay"', 'SettingsIcon(title: "Wallet et Apple Pay"'),
    ('Text("Apple ID, iCloud+, Media & Purchases")', 'Text("Apple ID, iCloud+, Médias et achats")'),
    ('Text("Home Network")', 'Text("Réseau domestique")'),
    ('Text("On")', 'Text("Activé")'),
    ('Text("Off")', 'Text("Désactivé")'),
    ('ContentUnavailableView("Contacts"', 'ContentUnavailableView("Contacts"'),
    ('ContentUnavailableView("Favorites"', 'ContentUnavailableView("Favoris"'),
    ('ContentUnavailableView("For You"', 'ContentUnavailableView("Pour vous"'),
    ('ContentUnavailableView("Search"', 'ContentUnavailableView("Rechercher"'),
    ('navigationTitle("All Inboxes")', 'navigationTitle("Toutes les boîtes")'),
    ('navigationTitle("Inbox")', 'navigationTitle("Boîte de réception")'),
    ('navigationTitle("Drafts")', 'navigationTitle("Brouillons")'),
    ('navigationTitle("Sent")', 'navigationTitle("Envoyés")'),
    ('navigationTitle("Junk")', 'navigationTitle("Indésirables")'),
    ('navigationTitle("Trash")', 'navigationTitle("Corbeille")'),
    ('navigationTitle("Archive")', 'navigationTitle("Archives")'),
    ('navigationTitle("VIP")', 'navigationTitle("VIP")'),
    ('title: "All Inboxes"', 'title: "Toutes les boîtes"'),
    ('title: "Inbox"', 'title: "Boîte de réception"'),
    ('title: "Drafts"', 'title: "Brouillons"'),
    ('title: "Sent"', 'title: "Envoyés"'),
    ('title: "Junk"', 'title: "Indésirables"'),
    ('title: "Trash"', 'title: "Corbeille"'),
    ('title: "Archive"', 'title: "Archives"'),
    ('title: "VIP"', 'title: "VIP"'),
]

def main():
    count = 0
    for path in ROOT.rglob("*.swift"):
        text = path.read_text(encoding="utf-8")
        original = text
        for old, new in REPLACEMENTS:
            text = text.replace(old, new)
        if text != original:
            path.write_text(text, encoding="utf-8")
            count += 1
            print(f"updated {path.name}")
    print(f"Done: {count} files")

if __name__ == "__main__":
    main()
