//
//  CurrencyData.swift
//  Youtube_Phantom_clone
//
//  Created by Sopheamen VAN on 13/3/25.
//

import Foundation

let currencyData: [CurrencyResponse] = [
    CurrencyResponse(
        name: "Ethereum",
        imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/279/large/ethereum.png",
        symbol: "ETH",
        network: "Ethereum",
        rate: "0.047 ETH",
        amount: "$187.20",
        subAmount: "+$5.32",
        type: 1,
        totalBalance: "$2,450.00",
        totalChange: "+$45.20",
        totalChangeType: 1,
        percentageChange: "+1.89%",
        marketCap: "$399B",
        totalSupply: "120M",
        circulatingSupply: "118M",
        maxSupply: "N/A",
        about: "Ethereum is a decentralized platform that runs smart contracts without downtime or third-party interference."
    ),
    CurrencyResponse(
        name: "USDC",
        imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/6319/large/usdc.png",
        symbol: "USDC",
        network: "Ethereum",
        rate: "105.23 USDC",
        amount: "$105.23",
        subAmount: "+$0.00",
        type: 1,
        totalBalance: "$1,005.00",
        totalChange: "+$5.00",
        totalChangeType: 1,
        percentageChange: "+0.5%",
        marketCap: "$27.6B",
        totalSupply: "32.6B",
        circulatingSupply: "32.6B",
        maxSupply: "N/A",
        about: "USDC is a stablecoin pegged to the US dollar, ensuring 1:1 backing by cash and cash-equivalents."
    ),
    CurrencyResponse(
        name: "Solana",
        imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/4128/large/solana.png",
        symbol: "SOL",
        network: "Solana",
        rate: "1.75 SOL",
        amount: "$166.15",
        subAmount: "+$3.45",
        type: 1,
        totalBalance: "$3,210.00",
        totalChange: "-$120.00",
        totalChangeType: 0,
        percentageChange: "-3.6%",
        marketCap: "$75B",
        totalSupply: "556M",
        circulatingSupply: "448M",
        maxSupply: "N/A",
        about: "Solana is a fast, secure, and censorship-resistant blockchain providing open infrastructure for global adoption."
    ),
    
    CurrencyResponse(
        name: "Polygon",
        imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/4713/large/polygon.png",
        symbol: "MATIC",
        network: "Polygon",
        rate: "32.65 MATIC",
        amount: "$24.36",
        subAmount: "+$0.12",
        type: 1,
        totalBalance: "$1,250.00",
        totalChange: "+$25.00",
        totalChangeType: 1,
        percentageChange: "+2.5%",
        marketCap: "$15B",
        totalSupply: "10B",
        circulatingSupply: "9B",
        maxSupply: "10B",
        about: "Polygon is a protocol and a framework for building and connecting Ethereum-compatible blockchain networks."
    ),
    CurrencyResponse(
        name: "Bitcoin",
        imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/1/large/bitcoin.png",
        symbol: "BTC",
        network: "Bitcoin",
        rate: "0.0034 BTC",
        amount: "$147.89",
        subAmount: "-$2.03",
        type: 0,
        totalBalance: "$95,918.00",
        totalChange: "-$3,838.16",
        totalChangeType: 0,
        percentageChange: "-3.85%",
        marketCap: "$1.89T",
        totalSupply: "19.82M",
        circulatingSupply: "19.82M",
        maxSupply: "21M",
        about: "Bitcoin is the first successful internet money based on peer-to-peer technology; whereby no central bank or authority is involved in the transaction."
    ),
    CurrencyResponse(
        name: "Avalanche",
        imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png",
        symbol: "AVAX",
        network: "Avalanche",
        rate: "2.83 AVAX",
        amount: "$102.94",
        subAmount: "+$1.78",
        type: 1,
        totalBalance: "$780.00",
        totalChange: "+$30.00",
        totalChangeType: 1,
        percentageChange: "+4.0%",
        marketCap: "$8.5B",
        totalSupply: "400M",
        circulatingSupply: "350M",
        maxSupply: "720M",
        about: "Avalanche is an open-source platform for launching decentralized applications and enterprise blockchain deployments."
    ),
    CurrencyResponse(
        name: "Litecoin",
        imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/15456/large/LrysCc5Q_400x400.jpg",
        symbol: "LTC",
        network: "Litecoin",
        rate: "3.20 LTC",
        amount: "$256.00",
        subAmount: "-$4.00",
        type: 0,
        totalBalance: "$1,200.00",
        totalChange: "-$40.00",
        totalChangeType: 0,
        percentageChange: "-3.2%",
        marketCap: "$18.5B",
        totalSupply: "84M",
        circulatingSupply: "73M",
        maxSupply: "84M",
        about: "Litecoin is a peer-to-peer cryptocurrency that enables instant, near-zero cost payments to anyone in the world."
    ),
    CurrencyResponse(
            name: "Chainlink",
            imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/877/large/chainlink-new-logo.png",
            symbol: "LINK",
            network: "Ethereum",
            rate: "10.25 LINK",
            amount: "$145.30",
            subAmount: "+$3.20",
            type: 1,
            totalBalance: "$1,450.00",
            totalChange: "+$25.00",
            totalChangeType: 1,
            percentageChange: "+2.5%",
            marketCap: "$8.2B",
            totalSupply: "1B",
            circulatingSupply: "467M",
            maxSupply: "1B",
            about: "Chainlink is a decentralized oracle network that enables smart contracts to securely interact with real-world data."
        ),
        CurrencyResponse(
            name: "Dogecoin",
            imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/18516/large/BUFF_KOIN.png",
            symbol: "DOGE",
            network: "Dogecoin",
            rate: "500 DOGE",
            amount: "$65.40",
            subAmount: "-$1.20",
            type: 0,
            totalBalance: "$540.00",
            totalChange: "-$15.00",
            totalChangeType: 0,
            percentageChange: "-2.7%",
            marketCap: "$10B",
            totalSupply: "132B",
            circulatingSupply: "132B",
            maxSupply: "N/A",
            about: "Dogecoin is an open-source cryptocurrency started as a joke but gained popularity through its active community."
        ),
        CurrencyResponse(
            name: "Cardano",
            imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/975/large/cardano.png",
            symbol: "ADA",
            network: "Cardano",
            rate: "150 ADA",
            amount: "$72.15",
            subAmount: "+$0.55",
            type: 1,
            totalBalance: "$680.00",
            totalChange: "+$10.00",
            totalChangeType: 1,
            percentageChange: "+1.5%",
            marketCap: "$13.2B",
            totalSupply: "45B",
            circulatingSupply: "34B",
            maxSupply: "45B",
            about: "Cardano is a blockchain platform for smart contracts that aims to deliver scalability, interoperability, and sustainability."
        ),
        CurrencyResponse(
            name: "Ripple",
            imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/44/large/xrp-symbol-white-128.png",
            symbol: "XRP",
            network: "Ripple",
            rate: "250 XRP",
            amount: "$123.45",
            subAmount: "+$2.45",
            type: 1,
            totalBalance: "$980.00",
            totalChange: "+$20.00",
            totalChangeType: 1,
            percentageChange: "+2.0%",
            marketCap: "$25B",
            totalSupply: "100B",
            circulatingSupply: "50B",
            maxSupply: "100B",
            about: "Ripple is a payment protocol and currency exchange network that offers fast, low-cost international transactions."
        ),
        CurrencyResponse(
            name: "Stellar",
            imageUrl: "https://proxycgassets.api.live.ledger.com/coins/images/100/large/fmpFRHHQ_400x400.jpg",
            symbol: "XLM",
            network: "Stellar",
            rate: "300 XLM",
            amount: "$89.60",
            subAmount: "-$0.90",
            type: 0,
            totalBalance: "$600.00",
            totalChange: "-$12.00",
            totalChangeType: 0,
            percentageChange: "-1.95%",
            marketCap: "$3.5B",
            totalSupply: "50B",
            circulatingSupply: "27B",
            maxSupply: "50B",
            about: "Stellar is a decentralized protocol designed to transfer digital currency to fiat money domestically and across borders."
        )
]
