import Foundation

enum AwesomeShowroomCatalog {
    static let tierApps: [String] = [
        "WhatsApp",
        "Signal",
        "Telegram",
        "Messenger",
        "Discord",
        "Teams",
        "Instagram",
        "TikTok",
        "Snapchat",
        "X",
        "Reddit",
        "LinkedIn",
        "Facebook",
        "Threads",
        "Pinterest",
        "Tinder",
        "Bumble",
        "Hinge",
        "Happn",
        "Spotify",
        "Apple Music",
        "Deezer",
        "SoundCloud",
        "YouTube Music",
        "Shazam",
        "Audible",
        "YouTube",
        "Netflix",
        "Disney+",
        "Prime Video",
        "Apple TV",
        "Twitch",
        "ChatGPT",
        "Gemini",
        "Claude",
        "Perplexity",
        "Grok",
        "Revolut",
        "Wise",
        "PayPal",
        "Binance",
        "Coinbase",
        "Amazon",
        "Uber",
        "Uber Eats",
        "Deliveroo",
        "Waze",
        "Google Maps",
        "Booking",
        "Airbnb",
        "Expedia",
        "Flighty",
        "TripAdvisor",
        "Strava",
        "Google Calendar",
        "Dropbox",
        "Zoom",
        "Kindle",
        "Banque",
        "Plans",
        "Fichiers",
    ]
}
